#cloud-config
package_update: true
package_upgrade: true

packages:
  - curl
  - ca-certificates
  - vim
  - postfix

runcmd:
  - set -ex

  # Install GitLab
  # https://about.gitlab.com/install/#debian
  - curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash

  # https://docs.gitlab.com/ee/administration/environment_variables.html
  - export EXTERNAL_URL="https://${gitlab_fqdn}"
  - export GITLAB_ROOT_PASSWORD="${gitlab_root_password}"

  - apt-get install gitlab-ce
