#cloud-config
package_update: true
package_upgrade: true

packages:
  - curl
  - ca-certificates
  - vim
  - postfix

runcmd:
  - set -ex

  # Install GitLab
  # https://about.gitlab.com/install/#debian
  - curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash
  - EXTERNAL_URL="https://${gitlab_fqdn}" apt-get install gitlab-ce
